services:
  db:
    image: postgres:16
    platform: linux/amd64
    container_name: postgres16_odoo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_dev_2024
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  odoo:
    image: bitnami/odoo:19
    platform: linux/amd64
    container_name: odoo19_dev
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ..:/bitnami/odoo/addons:ro
      - odoo-web-data:/bitnami/odoo
    environment:
      - ODOO_DATABASE_HOST=db
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=odoo
      - ODOO_DATABASE_PASSWORD=odoo_dev_2024
      - ODOO_DATABASE_NAME=lod_dev

volumes:
  odoo-db-data:
  odoo-web-data:
